name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-26.04

    steps:
    - uses: actions/checkout@v7
    - name: Check system
      run: |
        cat /etc/os-release
        nproc
        free -h
    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl3-dev libsdl3-ttf-dev libsdl3-image-dev
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
